// tokenizer_compat 用 sugarme/tokenizer 加载 tokenizer.json，
// 与 Python `tokenizers` 库（arktts_runtime/prompt.py 同款）生成的 baseline.json
// 做 100 条样本的严格 id/token/attention_mask 对比。
//
// 用法:
//
//	# 先跑 Python 生成基准
//	cd onnx_runtime/arktts_go/tools/tokenizer_compat
//	python3 gen_baseline.py
//
//	# 再跑 Go 对比
//	go run ./tools/tokenizer_compat \
//	    --tokenizer ../../model/tokenizer/tokenizer.json \
//	    --baseline ./baseline.json
//
// 退出码:
//
//	0  全部样本一致
//	1  存在不一致样本
//	2  环境/参数错误（找不到文件等）
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/sugarme/tokenizer"
	"github.com/sugarme/tokenizer/pretrained"
)

// baseline 结构与 gen_baseline.py 输出对齐
type baselineFile struct {
	TokenizerPath  string         `json:"tokenizer_path"`
	TokenizerSHA256 string        `json:"tokenizer_sha256"`
	SampleCount    int            `json:"sample_count"`
	SuccessCount   int            `json:"success_count"`
	FailureCount   int            `json:"failure_count"`
	Samples        []baselineItem `json:"samples"`
	Failures       []baselineFailure `json:"failures"`
}

type baselineItem struct {
	Index          int      `json:"index"`
	Text           string   `json:"text"`
	IDs            []int    `json:"ids"`
	Tokens         []string `json:"tokens"`
	AttentionMask  []int    `json:"attention_mask"`
}

type baselineFailure struct {
	Index int    `json:"index"`
	Text  string `json:"text"`
	Error string `json:"error"`
}

type diffKind string

const (
	diffIDsLen      diffKind = "ids_length"
	diffIDsValue    diffKind = "ids_value"
	diffTokensLen   diffKind = "tokens_length"
	diffTokensValue diffKind = "tokens_value"
	diffMaskLen     diffKind = "mask_length"
	diffMaskValue   diffKind = "mask_value"
	diffPanic       diffKind = "encode_error"
)

type sampleDiff struct {
	Index     int       `json:"index"`
	Text      string    `json:"text"`
	Kind      diffKind  `json:"kind"`
	GoError   string    `json:"go_error,omitempty"`
	PyIDs     []int     `json:"py_ids,omitempty"`
	GoIDs     []int     `json:"go_ids,omitempty"`
	PyTokens  []string  `json:"py_tokens,omitempty"`
	GoTokens  []string  `json:"go_tokens,omitempty"`
	PyMask    []int     `json:"py_mask,omitempty"`
	GoMask    []int     `json:"go_mask,omitempty"`
	FirstDiff int       `json:"first_diff_index,omitempty"` // -1 表示无差异
}

type report struct {
	TokenizerPath   string        `json:"tokenizer_path"`
	BaselinePath    string        `json:"baseline_path"`
	BaselineSHA256  string        `json:"baseline_tokenizer_sha256"`
	GoVocabSize     int           `json:"go_vocab_size"`
	TotalSamples    int           `json:"total_samples"`
	PassedCount     int           `json:"passed_count"`
	FailedCount     int           `json:"failed_count"`
	PyFailureCount  int           `json:"python_failure_count"`
	Diffs           []sampleDiff  `json:"diffs"`
}

func main() {
	// 默认路径相对于 arktts_go 工作目录，方便 `go run ./tools/tokenizer_compat/`
	defaultTokenizer := filepath.Join("..", "model", "tokenizer", "tokenizer.json")
	defaultBaseline := filepath.Join("tools", "tokenizer_compat", "baseline.json")

	tokenizerPath := flag.String("tokenizer", defaultTokenizer, "path to tokenizer.json")
	baselinePath := flag.String("baseline", defaultBaseline, "path to baseline.json generated by gen_baseline.py")
	showDiff := flag.Int("show-diff", 10, "print details of first N failed samples to stderr")
	strictTokens := flag.Bool("strict-tokens", true, "also compare token strings (not just IDs)")
	strictMask := flag.Bool("strict-mask", false, "also compare attention_mask")
	jsonOut := flag.Bool("json", false, "output report as JSON to stdout")
	flag.Parse()

	if err := run(*tokenizerPath, *baselinePath, *showDiff, *strictTokens, *strictMask, *jsonOut); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(2)
	}
}

func run(tokenizerPath, baselinePath string, showDiff int, strictTokens, strictMask, jsonOut bool) error {
	if _, err := os.Stat(tokenizerPath); err != nil {
		return fmt.Errorf("tokenizer.json not found: %w", err)
	}
	if _, err := os.Stat(baselinePath); err != nil {
		return fmt.Errorf("baseline.json not found (run gen_baseline.py first): %w", err)
	}

	raw, err := os.ReadFile(baselinePath)
	if err != nil {
		return fmt.Errorf("read baseline: %w", err)
	}
	var bl baselineFile
	if err := json.Unmarshal(raw, &bl); err != nil {
		return fmt.Errorf("parse baseline json: %w", err)
	}

	fmt.Fprintf(os.Stderr, "loading tokenizer: %s\n", tokenizerPath)
	// sugarme/tokenizer 在加载某些 tokenizer.json 时会 panic
	// （如 GPT2 pre-tokenizer 的 `(?!\S)` 负向 lookahead 不被 Go RE2 支持），
	// 用 recover 把 panic 转成友好错误。
	var tk *tokenizer.Tokenizer
	var loadErr error
	func() {
		defer func() {
			if r := recover(); r != nil {
				loadErr = fmt.Errorf("panic while loading tokenizer (sugarme/tokenizer compatibility issue): %v", r)
			}
		}()
		tk, loadErr = pretrained.FromFile(tokenizerPath)
	}()
	if loadErr != nil {
		return fmt.Errorf("load tokenizer: %w", loadErr)
	}
	fmt.Fprintf(os.Stderr, "tokenizer vocab size (with added tokens): %d\n", tk.GetVocabSize(true))

	rpt := report{
		TokenizerPath:  tokenizerPath,
		BaselinePath:   baselinePath,
		BaselineSHA256: bl.TokenizerSHA256,
		GoVocabSize:    tk.GetVocabSize(true),
		TotalSamples:   len(bl.Samples),
		PyFailureCount: len(bl.Failures),
	}

	for _, item := range bl.Samples {
		diff, ok := compareOne(tk, item, strictTokens, strictMask)
		if ok {
			rpt.PassedCount++
			continue
		}
		rpt.FailedCount++
		rpt.Diffs = append(rpt.Diffs, diff)
	}

	if jsonOut {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(rpt)
	} else {
		printReport(os.Stderr, rpt, showDiff)
	}

	if rpt.FailedCount > 0 {
		os.Exit(1)
	}
	return nil
}

func compareOne(tk *tokenizer.Tokenizer, item baselineItem, strictTokens, strictMask bool) (sampleDiff, bool) {
	inputSeq := tokenizer.NewInputSequence(item.Text)
	input := tokenizer.NewSingleEncodeInput(inputSeq)
	enc, err := tk.Encode(input, false)
	if err != nil {
		return sampleDiff{
			Index:   item.Index,
			Text:    item.Text,
			Kind:    diffPanic,
			GoError: err.Error(),
		}, false
	}

	goIDs := enc.Ids
	goTokens := enc.Tokens
	goMask := enc.AttentionMask

	// IDs 是最关键的字段（运行时只用 ids 喂模型）
	if len(goIDs) != len(item.IDs) {
		return sampleDiff{
			Index:    item.Index,
			Text:     item.Text,
			Kind:     diffIDsLen,
			PyIDs:    item.IDs,
			GoIDs:    goIDs,
			PyTokens: item.Tokens,
			GoTokens: goTokens,
		}, false
	}
	firstDiff := -1
	for i := range item.IDs {
		if goIDs[i] != item.IDs[i] {
			firstDiff = i
			break
		}
	}
	if firstDiff >= 0 {
		return sampleDiff{
			Index:     item.Index,
			Text:      item.Text,
			Kind:      diffIDsValue,
			PyIDs:     item.IDs,
			GoIDs:     goIDs,
			PyTokens:  item.Tokens,
			GoTokens:  goTokens,
			FirstDiff: firstDiff,
		}, false
	}

	if strictTokens {
		if len(goTokens) != len(item.Tokens) {
			return sampleDiff{
				Index:     item.Index,
				Text:      item.Text,
				Kind:      diffTokensLen,
				PyTokens:  item.Tokens,
				GoTokens:  goTokens,
				FirstDiff: -1,
			}, false
		}
		for i := range item.Tokens {
			if goTokens[i] != item.Tokens[i] {
				return sampleDiff{
					Index:     item.Index,
					Text:      item.Text,
					Kind:       diffTokensValue,
					PyTokens:  item.Tokens,
					GoTokens:  goTokens,
					FirstDiff: i,
				}, false
			}
		}
	}

	if strictMask {
		if !reflect.DeepEqual(goMask, item.AttentionMask) {
			kind := diffMaskLen
			if len(goMask) == len(item.AttentionMask) {
				kind = diffMaskValue
			}
			return sampleDiff{
				Index:  item.Index,
				Text:   item.Text,
				Kind:   kind,
				PyMask: item.AttentionMask,
				GoMask: goMask,
			}, false
		}
	}

	return sampleDiff{}, true
}

func printReport(w *os.File, rpt report, showDiff int) {
	fmt.Fprintln(w, strings.Repeat("=", 70))
	fmt.Fprintf(w, "tokenizer path       : %s\n", rpt.TokenizerPath)
	fmt.Fprintf(w, "baseline path        : %s\n", rpt.BaselinePath)
	fmt.Fprintf(w, "baseline sha256      : %s\n", rpt.BaselineSHA256)
	fmt.Fprintf(w, "Go vocab size        : %d\n", rpt.GoVocabSize)
	fmt.Fprintf(w, "total samples        : %d\n", rpt.TotalSamples)
	fmt.Fprintf(w, "  passed             : %d\n", rpt.PassedCount)
	fmt.Fprintf(w, "  failed             : %d\n", rpt.FailedCount)
	fmt.Fprintf(w, "python-side failures : %d (excluded from comparison)\n", rpt.PyFailureCount)
	fmt.Fprintln(w, strings.Repeat("-", 70))

	if rpt.FailedCount == 0 {
		fmt.Fprintln(w, "RESULT: ALL PASSED ✅")
		return
	}
	fmt.Fprintln(w, "RESULT: MISMATCH ❌")

	limit := showDiff
	if limit > len(rpt.Diffs) {
		limit = len(rpt.Diffs)
	}
	for i := 0; i < limit; i++ {
		d := rpt.Diffs[i]
		fmt.Fprintln(w, strings.Repeat("-", 70))
		fmt.Fprintf(w, "[#%d] index=%d kind=%s\n", i+1, d.Index, d.Kind)
		fmt.Fprintf(w, "text  : %q\n", truncate(d.Text, 120))
		if d.GoError != "" {
			fmt.Fprintf(w, "go error: %s\n", d.GoError)
			continue
		}
		if d.FirstDiff >= 0 {
			fmt.Fprintf(w, "first diff at token index: %d\n", d.FirstDiff)
		}
		fmt.Fprintf(w, "py ids (%d): %s\n", len(d.PyIDs), truncInts(d.PyIDs, 20))
		fmt.Fprintf(w, "go ids (%d): %s\n", len(d.GoIDs), truncInts(d.GoIDs, 20))
		if len(d.PyTokens) > 0 || len(d.GoTokens) > 0 {
			fmt.Fprintf(w, "py tokens  : %s\n", truncStrs(d.PyTokens, 20))
			fmt.Fprintf(w, "go tokens  : %s\n", truncStrs(d.GoTokens, 20))
		}
	}
	if remain := len(rpt.Diffs) - limit; remain > 0 {
		fmt.Fprintf(w, "... (%d more diffs omitted)\n", remain)
	}
	fmt.Fprintln(w, strings.Repeat("=", 70))
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

func truncInts(v []int, n int) string {
	if len(v) <= n {
		return fmt.Sprintf("%v", v)
	}
	return fmt.Sprintf("%v …", v[:n])
}

func truncStrs(v []string, n int) string {
	if len(v) <= n {
		return fmt.Sprintf("%v", v)
	}
	return fmt.Sprintf("%v …", v[:n])
}
